### ISSUE TITLE
Request: Include 2 gaming related patches (proton)..

### ISSUE THREAD

**Issue by oscarbg** [Gcenx/macOS_Wine_builds#113]
Hi,
can add two patches for testing gaming things on Mac on your upcoming 9.21 build?..
they are on Proton.. they are small patches.. and apply cleanly at least latest 9.20..
requested to Kron4ek and already included in latest 9.19 and 9.20 builds..
1) HAGS patch (needed by all DLSS3FG games using Streamline so allows testing DLSS3FG 2 FSR3 wrappers on Mac)
more info here:
https://github.com/Kron4ek/Wine-Builds/issues/125
latest working patch:
https://github.com/Kron4ek/Wine-Builds/issues/125#issuecomment-2390866596
2) HDR Alan Wake 2 patch (allows Alan Wake 2 to correctly detect HDR displays)
https://github.com/Kron4ek/Wine-Builds/issues/150
https://github.com/ValveSoftware/wine/commit/1182ef740346c62b76992f425593fa72e23203a7.diff

thanks..

**Comment by relalis** [comment]
This is unlikely to happen unless they get upstreamed to wine, as gcenx publishes unmodified wine builds with only the dylib fix (which is a runtime bug on macOS). If you're interested in testing these patches, why not just apply them yourself?
