### ISSUE TITLE
wine-9.21: Removed the releases as they failed at wineboot

### ISSUE THREAD

**Issue by Gcenx** [Gcenx/macOS_Wine_builds#114]
Not sure if the problem is upstream or some of the applied patches.

**Comment by 1146839821** [comment]
I applied the msync patch (1001 develop msync. diff), which can cause compilation issues
`completion.c:95:5: error: incompatible function pointer types initializing 'unsigned int (*)(struct object *, enum msync_type *)' with an expression of type 'void (struct object *, struct wait_queue_entry *)' [-Wincompatible-function-pointer-types]
   95 |     completion_wait_satisfied,      /* satisfied */`
