### ISSUE TITLE
wine desktop is broken

### ISSUE THREAD

**Issue by lyssdod** [Gcenx/macOS_Wine_builds#16]
Hi,

Thanks for the build! The issue is that highlighted virtual desktop checkbox has no effect – I cannot force wine to display a desktop. Tried with both latest stable and devel versions (currently on 5.22). Also it seems that it's using macdriver by default, do you know how do I force it to X11? I have XQuartz installed. 

![Screenshot 2020-12-21 at 14 29 40](https://user-images.githubusercontent.com/2615950/102782243-53356e80-4399-11eb-9f9b-8f5b540d852c.png)
I'm on 10.14

**Comment by Gcenx** [comment]
Wine on macOS has defaulted to macdriver since it was added. Yes virtual desktop only works on X11. Install winetricks and setup `WINEPREFIX` then run the following command.

```
winetricks macdriver=x11
```

I still think this checkbox should be disabled unless running X11 display driver but that’s upstream wine for you.
