### ISSUE TITLE
Does not work/run on macOS 10.13.

### ISSUE THREAD

**Issue by pbobbenb** [Gcenx/macOS_Wine_builds#18]
According to the text on the releases/downloads page it has been tested on macOS 10.9, but it does not run on 10.13.
Unpacking the archive gives a ghosted icon with a circle that has a slash trough it.
And double clicking the icon gives this message:

This version of the program "Wine Stable" can not be used with this version of macOS.
You have macOS 10.13.6. Program requires macOS 10.14 or later.

Is it possible to fix this?

**Comment by Gcenx** [comment]
That seems odd when the info.plist is listed for 10.9.0, instead try installing using my brew tap and launch directly from terminal.

**Comment by benknam** [comment]
> That seems odd when the info.plist is listed for 10.9.0, instead try installing using my brew tap and launch directly from terminal.

Successfully installed via brew, app with a ban cover in application folder. Running good under Term.

**Comment by Gcenx** [comment]
The actual wine compile is tested within an OSX 10.9 VM, however I don’t ever use the app wrapper.

I commonly use wine via terminal or within Wineskin as an Engine.

**Comment by pbobbenb** [comment]
Yes, it works fine from terminal, which is were I always start WinUAE anyway, also the only program I use Wine for.
Don't know why I didn't think of trying to run it from the command line, but well you always learn something new :-)
So, I guess this issue can be closed, since it does work, just not from the icon, or what do you think?

**Comment by Gcenx** [comment]
No it’s still useful to know that the launcher doesn’t work on macOS High Sierra as that’s my new target starting with Wine-6.1.

The runtime is already rebuilt to target macOS High Sierra and later, just need to rebuild the launcher and rebuild Wine-6.0 with a couple of Apple Silicon patches that were officially added into Wine-6.1.

**Comment by pbobbenb** [comment]
Ok, good to know!
