### ISSUE TITLE
Current build won't launch on m1 MacBook pro

### ISSUE THREAD

**Issue by amarant24** [Gcenx/macOS_Wine_builds#21]
I click the app, it bounces once and then it closes automatically.

Step to reproduce - try to launch the app 100% of the time.

Am I missing something? Manual installation does the same.

**Comment by Gcenx** [comment]
If you installed with the provided brew command it should launch a terminal session, but in all honestly I don’t even launch using the app.

After installing with brew all the needed binaries will be added to $PATH, you can now launch wine(64) directly without needing to interact with the actual app.

**Comment by amarant24** [comment]
How do you use it with terminal?

**Comment by Gcenx** [comment]
Once you've installed the selected package you launch `Terminal`

And just type `wine64`
<img width="567" alt="Screen Shot 2021-03-09 at 10 19 10 PM" src="https://user-images.githubusercontent.com/38226388/110571397-7e706400-8125-11eb-8792-6ce6f254bdc9.png">
As you have an M1 system you'll only have access to `wine64`
