### ISSUE TITLE
0009:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed

### ISSUE THREAD

**Issue by AnupPlays** [Gcenx/macOS_Wine_builds#22]
When trying to run an .exe on MacOS Big Sur, this error is popping up. Full logs below:

err:thread:get_image_addr dyld image info is above 4GB limit for 32-bit-on-64-bit process
000b:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
000d:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0010:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0017:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
001d:err:plugplay:process_IOService_Device object 0x6303
0019:err:plugplay:load_function_driver AddDevice failed for driver L"winebus", status 0xc0000002.
001d:err:plugplay:process_IOService_Device Unable to create plug in interface for USB deviceobject 0x6307
001d:err:plugplay:process_IOService_Device Unable to create plug in interface for USB deviceobject 0x630b
001d:err:plugplay:process_IOService_Device Unable to create plug in interface for USB deviceobject 0x630f
001d:err:plugplay:process_IOService_Device Unable to create plug in interface for USB deviceobject 0x6313
001d:err:plugplay:process_IOService_Device Unable to create plug in interface for USB deviceobject 0x6317
001d:err:plugplay:process_IOService_Device Unable to create plug in interface for USB deviceobject 0x631b
001d:err:plugplay:process_IOService_Device Unable to create plug in interface for USB deviceobject 0x631f
001d:err:plugplay:process_IOService_Device object 0x8a1f
001d:err:plugplay:process_IOService_Device object 0x8703
001f:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0009:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed

**Comment by Gcenx** [comment]
This issue has nothing to do with the upstream wine packages provided here.

The appropriate place for this issue would be https://github.com/Gcenx/homebrew-wine.
