### ISSUE TITLE
Error running 6.11 on 10.14.6 (Mojave)

### ISSUE THREAD

**Issue by tobbi** [Gcenx/macOS_Wine_builds#23]
When I start 6.11 on 10.14.6, I get the following error.
```
$ /Applications/Wine\ Devel.app/Contents/MacOS/wine
dyld: lazy symbol binding failed: Symbol not found: _objc_opt_new
  Referenced from: /Applications/Wine Devel.app/Contents/MacOS/wine (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

dyld: Symbol not found: _objc_opt_new
  Referenced from: /Applications/Wine Devel.app/Contents/MacOS/wine (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

Abort trap: 6
```

**Comment by Gcenx** [comment]
That’s rather annoying it should have used the i386 slice on Mojave and only used the x86_64 slice on Catalina and later.

**Comment by Gcenx** [comment]
@tobbi I see the problem you attempted to directly launch `/Applications/Wine Devel.app/Contents/MacOS/wine` via terminal that does indeed throw an error.

Was there a reason for directly launching the `wine` binary wrapper?, as the actual wine binaries are located in '/Applications/Wine Devel.app/Contents/Resources/wine/bin'

Testing directly launching the app bundle and launched Terminal session correctly when provided the requested permission, also tested "open with" this also functioned correctly.

**Comment by tobbi** [comment]
Okay, I tried that, but a) it takes a while to run and b) the terminal window that gets opened shows this:
```
################################################################################
#                           Wine Is Not an Emulator                            #
################################################################################

/Applications/Wine Devel.app/Contents/Resources/start/bin/winehelp: line 41: wine: command not found
 Welcome to .

 In order to start a program:
   .exe: wine program.exe
   .msi: wine msiexec /i program.msi

 If you want to configure wine:
   wine winecfg

 To get information about app compatibility:
   appdb Program Name
```

Entering `wine` into the console window tells me that wine wasn't found.

**Comment by Gcenx** [comment]
Trash the app and download it again preferably with my brew tap so `wine` gets installed into your user `$PATH`

Look like you download it before I’d re-uploaded.

**Comment by tobbi** [comment]
You're right. It's working now. Thanks!
