### ISSUE TITLE
MacOS 11.6 Big Sur latest breaks DX11 functionality (Vulkan renderer)

### ISSUE THREAD

**Issue by Rmilkmilk** [Gcenx/macOS_Wine_builds#27]
I updated my Mac mini 2018 from 11.5.2 to 11.6, and now find that all of my previous Wineskin / Wine App builds fail to run for DirectX 11 using the Vulcan. Previously they worked just fine. Specifics:
Had Wine Build 6.16 downloaded and working fine with Vulkan support for DX11.
Now the same application fails with a message that the D3D shader isn't supported:

0298:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0298:fixme:dxgi:dxgi_output_GetDisplayModeList iface 0x36ed060, format DXGI_FORMAT_R8G8B8A8_UNORM, flags 0x2, mode_count 0x11f110, modes 0x0 partial stub!
0298:fixme:dxgi:dxgi_output_GetDisplayModeList iface 0x36ed060, format DXGI_FORMAT_R8G8B8A8_UNORM, flags 0x2, mode_count 0x11f110, modes 0xa491270 partial stub!
0298:fixme:dxgi:DXGID3D10CreateDevice Ignoring flags 0x80.
0298:fixme:winediag:wined3d_select_feature_level None of the requested D3D feature levels is supported on this GPU with the current shader backend.

Do you have any ideas on this?
Tried refresh/rebuild the bottle, no effect.

**Comment by Gcenx** [comment]
The packages provided ship the stock MoltenVK so don't support macOS_DXVK, Wineskin ships a custom MoltenVK to enable macOS_DXVK.

This repository's focus is to replace the depreciated Winehq packages until were done getting everything in-place for _official Winehq packages. If you're having issues with Wineskin please open an issue on https://github.com/Gcenx/WineskinServer

**Comment by Rmilkmilk** [comment]
Got it. Thank you for the reply. I'll verify I am using the updated Wineskin server for the build, and post there if it's still a problem.

**Comment by Rmilkmilk** [comment]
Thanks for the answer. The libs in the WineSkin Framework directory were not being used. In case anyone else finds it useful, I was able to fix this by removing the shared libs in the wine install directory (wine/lib/* files) which forced the libs to be used from the WineSkin wrapper Frameworks directory. Back to working as expected. Thank you!

**Comment by Gcenx** [comment]
Oh you repackaged the wine packages here and used them in Wineskin no wonder you had issues.

Wineskin engines _usually_ don’t include any libraries and instead use what’s provided by the wrappers /Frameworks directory.

WineskinLauncher (along with the builds here) default to reading `@loader_path/../../` (wine/lib & wine/lib64) for libraries then /opt/local/lib, /opt/X11/lib and finally fallback to normal system library locations.

I’m currently not providing more recent Engines for Wineskin until upstream is done with the 32-on-64 implementation is completed.

**Comment by Rmilkmilk** [comment]
Thank you for the response. I'll keep this issue in mind with WineSkin and Wine builds. I understand the whole 32-bit on 64-bit thunking is not a trivial task to implement. I've supported CrossOver with a subscription in the hopes they can get support on newer MacOS releases so I can run older software.
Yes, I'm leveraging your compiled package because it was an easier task than trying to homebrew my own. I saw the DYLIB_PATH setup and figured out the issue was specific to the Molten dylibs. Because the WineHQ site doesn't offer any Mac executables, I found yours were a great source instead. Also, donated to your project here to support your work that makes my life easier, and hope that others support you as well!

**Comment by Gcenx** [comment]
From wine-6.8 you can simply run 
```
cd (path to wine)/lib
rm *.dylib
```
And you’ll be hood to go as the libwine.dylib is now in another location.

Winehq will be getting newer macOS packages by wine-7.0 going off our current timeline, that’s assuming nothing weird happens between my finishing up the custom gstreamer “Portfiles”

Purchasing a CrossOver macOS license is one of the best way to keep CodeWeavers improving wine on macOS, even if it’s just to make there life easier (32-on-64 rebasing is a PITA)

Once everything is in place the Winehq macOS wiki sections will be updated with more in-depth build instructions, while we don’t believe many users will make use of them having them available should be useful.

Thank you for the support it’s always appreciated.

**Comment by Rmilkmilk** [comment]
Thank you again. Will definitely keep pitching in dollars to you and CodeWeavers. Like I said, you make it so I don't have to manage a HomeBrew setup in addition to my software dev day job 👍 
I can understand that 32-bit thunking onto 64-bit is a true PITA. Almost a trans-piler type of thing without the thanks for the difficulty.
The new 6.2 release has some newer dylibs, so thanks for confirming that I can move them out of the way as a workaround for now until a newer CrossOver or WineSkin is ready.
