### ISSUE TITLE
Detected virus in winedevice.exe, rundll32.exe, extrac32.exe prevents Homebrew installation

### ISSUE THREAD

**Issue by tschudin** [Gcenx/macOS_Wine_builds#31]
Installing ```wine-stable``` on a Apple M1 device (macOS Monterey 12.1) fails because of antivirus software (Microsoft Defender ATP), see attached screenshots

---

<img width="649" alt="Screenshot 2021-12-29 at 18 06 34" src="https://user-images.githubusercontent.com/3949826/147687097-a518faf7-c83c-4d98-a805-6cc01548fc96.png">

---

![Screenshot 2021-12-29 at 18 07 37](https://user-images.githubusercontent.com/3949826/147687212-7d3bcf39-caf0-41c7-87a1-b7c0f482ac15.png)

---

<img width="257" alt="Screenshot 2021-12-29 at 18 06 06" src="https://user-images.githubusercontent.com/3949826/147687134-1f38a7ef-e77a-4719-a60b-754b050fcb75.png">

**Comment by Gcenx** [comment]
A copy/paste from https://github.com/Gcenx/WineskinServer

# FAQ
### My Antivirus says it's a VIRUS!!!
You need to contact your AntiVirus/AntiMalware vender to connect these false positives.\
This started once wine moved to using *Mingw-gcc* to compile PE binaries.

__See the following examples__
- [CrossOver 19 and anti virus programs](https://www.codeweavers.com/support/forums/general/?t=27;msg=222870)
- [Windows Defender detects Occamy.c trojan in steam proton 5.0 folder](https://github.com/ValveSoftware/Proton/issues/3593)

See the report from [VIRUSTOTAL](https://www.virustotal.com/gui/url/52f16c47ae7fdd8fb00c46e2b777d54fcfa338acd4385fc3ce2b4f2368d5a340/summary)
