### ISSUE TITLE
Understanding release names/meanings?

### ISSUE THREAD

**Issue by sygibson** [Gcenx/macOS_Wine_builds#33]
Thank you for pulling this together !  Great resource.

I was trying to understand the differences between `stable`, `deve`l, and `staging` release tagged versions.

`stable` is pretty easy - it's currently pinned to 7.0
I see that both `devel` and `staging` versions have been release in 7.0 through 7.3 versions.

My question revolves more around .... "what's the difference between the `devel` and `staging` versions"?

**Comment by Gcenx** [comment]
wine-devel is upstream wine point releases every two weeks.

<br>

[wine-staging](https://github.com/wine-staging/wine-staging)
> **Wine Staging** is the testing area of winehq.org. It contains bug fixes and features, which have not been integrated into the development branch yet. The idea of Wine Staging is to provide experimental features faster to end users and to give developers the possibility to discuss and improve their patches before they are integrated into the main branch. More information about Wine Staging can also be found [on the WineHQ wiki](https://wiki.winehq.org/Wine-Staging).

**Comment by sygibson** [comment]
Great - thank you - appreciate  the fast response and details.
