### ISSUE TITLE
Trojan in homebrew stable install of Wine

### ISSUE THREAD

**Issue by paul-hammant** [Gcenx/macOS_Wine_builds#35]
Refer: 

https://www.virustotal.com/gui/file/7073edb2bb06f9e914ebf28439c48fe99e1715d62690251e267110f3f6fb28c4?nocache=1

https://github.com/Homebrew/discussions/discussions/3255

**Comment by Gcenx** [comment]
# FAQ
### My Antivirus says it's a VIRUS!!!
You need to contact your AntiVirus/AntiMalware vender to connect these false positives.\
This started once wine moved to using *Mingw-gcc* to compile PE binaries.

__See the following examples__
- [CrossOver 19 and anti virus programs](https://www.codeweavers.com/support/forums/general/?t=27;msg=222870)
- [Windows Defender detects Occamy.c trojan in steam proton 5.0 folder](https://github.com/ValveSoftware/Proton/issues/3593)

Known false positives the same thing will also happen with my `wine` brew formula that’s built via GitHub actions or even when built locally.
