### ISSUE TITLE
Wine 7.12 release?

### ISSUE THREAD

**Issue by oscarbg** [Gcenx/macOS_Wine_builds#37]
Hi,

just curious if you are going skip 7.12 release for some reason seeing in 5 days we will have 7.13..
mainly interested by new VKD3D 1.4 integration..

BIG THANKS as always for you work!

**Comment by Gcenx** [comment]
Just been busy they've been sitting built on my Desktop since the 7th just needed to package them up and upload.

I'll always first push to [macports-wine](https://github.com/Gcenx/macports-wine) before making the distributions that get uploaded here.

**Comment by Gcenx** [comment]
The uploading took longer than usual but wine-7.12 packages can now be grabbed from the releases section and from brew whenever the casks get updated.

**Comment by oscarbg** [comment]
thanks!
