### ISSUE TITLE
Internal Error on newest build, macOS Monterey 12.5, M1 MacBook Pro

### ISSUE THREAD

**Issue by KnedlikMCPE** [Gcenx/macOS_Wine_builds#39]
Hello,

When I try running any .exe, the newest build as of writing throws an internal error of ShellExecuteEx. I'm not sure if this is a mistake on my end, your end, or Wine's end. Could you please help me out resolve this in case it's one of the first two cases?

Thank you in advance,
-Knedlik

**Comment by Gcenx** [comment]
If you run say `wine64 winecfg` does it launch for you?

**Comment by KnedlikMCPE** [comment]
winecfg runs perfectly fine. No errors there, just when running an .exe.

**Comment by Gcenx** [comment]
As long as the exe is 64Bit and launches I wouldn’t worry about it too much, just file a Bugzilla

**Comment by KnedlikMCPE** [comment]
It is indeed 64-bit, but it affects more exes than it doesn't. And no, it doesn't launch. I will try troubleshooting with the people on Wine forums, but I will leave this issue open if you have any more suggestions.

**Comment by zrubinrattet** [comment]
@KnedlikMCPE any update from the Wine forums? I too am experiencing the same issue. Thanks!

**Comment by Gcenx** [comment]
Bugs need to be reported via https://bugs.winehq.org/ as the wine developers seldom check the forums.
