### ISSUE TITLE
Update Wine Stable 5.0.2

### ISSUE THREAD

**Issue by lpla** [Gcenx/macOS_Wine_builds#4]
Hi. Just wanted to notify about the latest stable release, 5.0.2, with lots of fixes, in case that it could be built and included in the "tap":

https://source.winehq.org/git/wine.git/?a=shortlog;h=refs/tags/wine-5.0.2

Thank you for this brew tap repo!

**Comment by Gcenx** [comment]
I had seen the new wine-stable version, https://github.com/Gcenx/macports-wine/commit/6d0a050de8bc3bb6b6c24ed74fc6fc0560e599ee around the same time I made the above commit the meson package was changed to use crossfile this has caused some headaches.

I’m hoping to get around to building the package sometime tonight.

**Comment by lpla** [comment]
Great! Thank you! If I could help with anything, just let me know here. I will test it as soon as I get the update.

**Comment by Gcenx** [comment]
Taken longer then expected but Wine-Stable-5.0.2 is now uploaded and the tap was also updated.

**Comment by lpla** [comment]
Working great! Thank you!
