### ISSUE TITLE
Build with epoll-shim

### ISSUE THREAD

**Issue by FlyGoat** [Gcenx/macOS_Wine_builds#40]
Hi,

Currently wine executable complains:
```
00dc:fixme:esync:do_esync eventfd not supported on this platform.
```

This can be easily fixed by building wine with [epoll-shim](https://github.com/jiixyj/epoll-shim), which emulates EventFD with kqueue.

Ref: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=246426

Thanks.

**Comment by Gcenx** [comment]
I’ve reached out to the staging maintainers to see if there willing to expand the eventfd patchset to handle this.

Outside of staging accepting the proposal it would require building epoll-shim as a static library.

**Comment by Gcenx** [comment]
I’ve reached out to my fellow maintainer and they believe well first need to verify _if_ adding this gives any benefit over just removing the fixme.

Waiting to hear back from the staging maintainers for possible test cases to see if there’s really any improvement by adding this.

The simply solution is to skip applying the `eventfd_synchronization` patchset.

**Comment by Gcenx** [comment]
I’ve attempted this and esync starts up then companies about an invalid command 20

Guess I’ll go with simply disabling the patchset as planned.

**Comment by Gcenx** [comment]
Here's the result of attempting to make use of `epoll-shim`
```
gcenx@Deans-Mac-mini ~ % export WINEESYNC=1
gcenx@Deans-Mac-mini ~ % wine64 explorer   
esync: up and running.
Protocol error: process 0020: sendmsg: Invalid argument
```

So unless Zeb feels like modifying `eventfd_synchronization` patchset to work with `epoll-shim` I'll just be skipping the patchset going forward.
