### ISSUE TITLE
staging upload damaged?

### ISSUE THREAD

**Issue by core-code** [Gcenx/macOS_Wine_builds#43]
<img width="505" alt="Screenshot 2022-09-27 at 17 50 20" src="https://user-images.githubusercontent.com/1261954/192574370-132372b1-9099-4487-ab2a-e25b2c71224b.png">

**Comment by Gcenx** [comment]
Can you confirm if your able to extract wine-devel without problem?

I’m currently at work so can’t verify anything currently but the staging archive is smaller than the devel archive, the upload it’s self shouldn’t be an issue as GitHub won’t make a partial upload visible. Maybe the keka screwed up the compression.

**Comment by Gcenx** [comment]
Temporarily changed 7.18 tag to pre-release until this can be resolved.

**Comment by Jason2866** [comment]
probably keka. I had issues with too. I deleted from my Apple M1 Air. Using now onboard cli tools. No more problems.

**Comment by core-code** [comment]
yes "devel" decompresses fine, but only "staging" doesn't. it is also 20 MB smaller. i suspect its a truncated upload.

"staging" both fails to decompress using Apple's built-in decompressor as well as using "Keka".

**Comment by Jason2866** [comment]
> > probably keka. I had issues with too. I deleted from my Apple M1 Air. Using now onboard cli tools. No more problems.
> 
> Usually only extract is an issue due to it propagating the quarantine flag.

No, keka corrupted files during compress. I searched a while why my builded gcc toolchains did not work.

**Comment by Gcenx** [comment]
> No, keka corrupted files during compress. I searched a while why my builded gcc toolchains did not work.

In this case it actually wasn't keka, it was really was an upload issue and github seemed fine with the file....

Re-uploaded the staging archive and this time it's not missing 20MB it's slightly larger than devel, tested extracting the archive before uploading.

**Comment by core-code** [comment]
thanks
