### ISSUE TITLE
Wow64 in 7.18?

### ISSUE THREAD

**Issue by Atemu** [Gcenx/macOS_Wine_builds#44]
According to the [release notes](https://www.winehq.org//announce/7.18), wine 7.18 should support Wow64 on macOS.

Your release notes state that

> Only wine64 will function via Rosetta2

however.

What exactly is the status on this?

**Comment by Gcenx** [comment]
See https://www.winehq.org/mailman3/hyperkitty/list/wine-devel@winehq.org/thread/DVCBFD6JUEOMETHFHQC5BT6DBYKG47YJ/

**Comment by Atemu** [comment]
Thanks!

**Comment by Gcenx** [comment]
As per upstream I shouldn’t apply those patches as it breaks printing globally, it also doesn’t currently work as you l’d expect.

Once this all lands in upstream it will be enabled.
