### ISSUE TITLE
Issues on Ventura

### ISSUE THREAD

**Issue by un-creative** [Gcenx/macOS_Wine_builds#46]
Whenever I execute a wine64 command i just get the error code

'preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
Application could not be started, or no application associated with the specifie
d file.
ShellExecuteEx failed: Internal error.'

or with wine64 winecfg i got 

'preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
00c4:fixme:imm:ImeSetActiveContext (0x35b1b0, 1): stub
00c4:fixme:imm:ImmReleaseContext (0000000000010054, 000000000035B1B0): stub
00cc:fixme:imm:ImeSetActiveContext (0x357d10, 0): stub
00cc:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000357D10): stub'

**Comment by Gcenx** [comment]
> Application could not be started, or no application associated with the specifie
d file.

This sounds like you’ve attempted to run a 32Bit Windows binary, many installers are actually 32Bit even if they install 64Bit binaries.

Im assuming winecfg loaded correctly?

I’m simply ignoring the preloader spam about reserving memory, that would need to be adjusted upstream.

**Comment by Gcenx** [comment]
Also what wine version are you using exactly?

**Comment by un-creative** [comment]
the most recent wine-stable

**Comment by Gcenx** [comment]
From wine-8.10 wow64 support has been merged in officially, at least 32Bit installers should become usable now.

I’ve pushed wine-8.10 packages, the brew casks will get updated at some point.
