### ISSUE TITLE
Corrupted release for Wine Staging 7.20

### ISSUE THREAD

**Issue by hannesbraun** [Gcenx/macOS_Wine_builds#47]
The latest release of Wine Staging (7.20) seems to be corrupted. I cannot unpack the archive provided via GitHub releases. (See also Homebrew/homebrew-cask-versions#15081.)

**Comment by Gcenx** [comment]
@hannesbraun re-uploaded the archive hopefully it's fine now, heading out

**Comment by hannesbraun** [comment]
Looks good. Thank you very much!

**Comment by Gcenx** [comment]
Now if only GitHub would stop this habit of corrupting the second upload in a queue…
