### ISSUE TITLE
Error input string

### ISSUE THREAD

**Issue by leduyquy** [Gcenx/macOS_Wine_builds#50]
Hi.

i have issue input string to 1 app .exe. 

it is not imported directly into the application but is shown in the box next to it and there is no way to enter it directly into the application.

the box it crashes as soon as I write this report and there is no way to turn it off other than by turning off wine

Can someone tell me what to do?

**Comment by Gcenx** [comment]
Not a packing issue, you’d need to report this via Winehq Bugzilla
