### ISSUE TITLE
Wine 8.0-rc1 

### ISSUE THREAD

**Issue by aliankarali** [Gcenx/macOS_Wine_builds#52]
Could you please update wine-devel cask with the version 8.0-rc1?

**Comment by Gcenx** [comment]
> Ah alright, no worries. I guess I'll just have to wait couple of weeks then. I was just hoping that maybe old versions of world of warcraft will now be playable on m1 macs but that is a faint hope anyway.

If that we’re a 32Bit client it still won’t work as upstream hasn’t merged all the relevant WoW64 patches as it breaks printers and it also currently doesn’t work right (I’ve been testing each release)

**Comment by Gcenx** [comment]
The remaining WoW64 patches are _not_ merged.

Also there’s no point even attempting to make use of those patches as explained above.

Even with when the WoW64 patchset gets applied it failed to generate a wineprefix and even after manually generating one it failed to launch anything. I’ll start opening bugs upstream after wine-8.0 lands as right now it’s the code freeze so not much point.

**Comment by aliankarali** [comment]
I see. Thanks for the explanation.
