### ISSUE TITLE
libSystem.B.dylib (no such file)

### ISSUE THREAD

**Issue by alessandro893** [Gcenx/macOS_Wine_builds#54]
MacOS: 12.4
MacPro: 5.1

CPU: Dual X5680
GPU: Radeon Vega 64
RAM: 96GB

App not working, it tries to access shared cache object "libSystem.B.dylib", and can't find it.

Is it related to Xcode SDK version?

Wine: **Not working** (tested versions: 5.0-8.2)
Crossover: **Not working** (tested versions: 12-22.1)
Wine-crossover: **Working**  (works only with root user, but not as good as Wineskin)
Wineskin Winery: **Working** (works very good)

LOG:
`mac:~ alexander$ sudo WINEPREFIX=/Volumes/Backup/Applications/Wine/Wine-root /Applications/Wine\ Staging.app/Contents/Resources/wine/bin/wine64 /Volumes/Backup/Applications/Worms\ Armageddon.app/Contents/SharedSupport/prefix/drive_c/Program\ Files/Worms\ Armageddon/WA.exe 
002c:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
002c:fixme:winediag:LdrInitializeThunk wine-staging 8.2 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
0048:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
0050:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
0050:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0050:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0050:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0050:err:ole:start_rpcss Failed to open RpcSs service
0048:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0048:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0048:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0048:fixme:imm:ImeSetActiveContext (0000000000010026, 0): stub
0048:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000010026): stub
002c:fixme:imm:ImeSetActiveContext (000000000001005C, 1): stub
002c:fixme:imm:ImmReleaseContext (000000000001005A, 000000000001005C): stub
0078:err:winedevice:ServiceMain Failed to load L"C:\\windows\\system32\\win32k.sys"
0078:err:winedevice:ServiceMain Failed to load L"C:\\windows\\system32\\drivers\\dxgkrnl.sys"
0078:err:winedevice:ServiceMain Failed to load L"C:\\windows\\system32\\drivers\\dxgmms1.sys"
008c:err:setupapi:SetupDefaultQueueCallbackW copy error 1812 L"@C:\\windows\\system32\\drivers\\wineusb.sys,-1" -> L"C:\\windows\\inf\\wineusb.inf"
008c:fixme:file:NtLockFile I/O completion on lock not implemented yet
008c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
dyld[92979]: Library not loaded: /usr/lib/libSystem.B.dylib
  Referenced from: /Applications/Wine Staging.app/Contents/Resources/wine/bin/wine-preloader
  Reason: tried: '/usr/lib/libSystem.B.dylib' (no such file), '/usr/local/lib/libSystem.B.dylib' (no such file)
008c:err:msi:execute_command unable to execute command 1359
dyld[92981]: Library not loaded: /usr/lib/libSystem.B.dylib
  Referenced from: /Applications/Wine Staging.app/Contents/Resources/wine/bin/wine-preloader
  Reason: tried: '/usr/lib/libSystem.B.dylib' (no such file), '/usr/local/lib/libSystem.B.dylib' (no such file)
008c:err:msi:execute_command unable to execute command 1359
008c:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
008c:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
dyld[92999]: Library not loaded: /usr/lib/libSystem.B.dylib
  Referenced from: /Applications/Wine Staging.app/Contents/Resources/wine/bin/wine-preloader
  Reason: tried: '/usr/lib/libSystem.B.dylib' (no such file), '/usr/local/lib/libSystem.B.dylib' (no such file)
0110:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
wine: configuration in L"/Volumes/Backup/Applications/Wine/Wine-root" has been updated.
0110:fixme:hid:handle_IRP_
MN_QUERY_ID Unhandled type 00000005
0110:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0110:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
dyld[93016]: Library not loaded: /usr/lib/libSystem.B.dylib
  Referenced from: /App
lications/Wine Staging.app/Contents/Resources/wine/bin/wine-preloader
  Reason: tried: '/usr/lib/libSystem.B.dylib' (no such file), '/usr/local/lib/libSystem.B.dylib' (no such file)
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: Internal error.`

Wine 8.2 (root user)
[wine_8-2_error-root.txt](https://github.com/Gcenx/macOS_Wine_builds/files/10833066/wine_8-2_error-root.txt)

Wine 8.2 (user)
[wine_8-2_error_user.txt](https://github.com/Gcenx/macOS_Wine_builds/files/10833068/wine_8-2_error_user.txt)

Wine-crossover (works)
[wine-crossover-working.txt](https://github.com/Gcenx/macOS_Wine_builds/files/10833067/wine-crossover-working.txt)

**Comment by Jason2866** [comment]
Seems to be you Hackintosh setup. Versions 8.x are all running well on Apple M1 Air 2020 with Mac OS Ventura.

**Comment by alessandro893** [comment]
> Seems to be you Hackintosh setup. Versions 8.x are all running well on Apple M1 Air 2020 with Mac OS Ventura.

I have mac pro not a hackintosh pc build. My mac use opencore as bootloader, I also have intel macbook pro with same setup (opencore+monterey), where it works without errors. May be the problem is related to 'dyld_shared_cache_x86_64'. But if so, why wine64 inside wineskin working good and without this error?

**Comment by Gcenx** [comment]
> May be the problem is related to 'dyld_shared_cache_x86_64'.

I'd assume that's the case as you yourself confirmed the package is working on your other mac.

> But if so, why wine64 inside wineskin working good and without this error?

`wineskinlauncher` is _very_ heavy handed with it's environment this avoids a lot of potential issues.

Also noticed in the provided logs you're attempting to run a 32Bit game, that won't work in upstream wine currently even with some unmerged patches it doesn't get far with may 32Bit applications outside of CLI only applications.
