### ISSUE TITLE
"wine: could not load ntdll.so" out of the box error when trying to use wine-stable

### ISSUE THREAD

**Issue by AgentRG** [Gcenx/macOS_Wine_builds#56]
System: Intel-based macOS Catalina (10.15.7)

Steps:
1. Install wine-stable through Homebrew using `brew install --cask --no-quarantine wine-stable`
2. Try to run wine by typing in `winecfg` in Terminal
3. Get an error that reads:
```
wine: could not load ntdll.so: dlopen(/Applications/Wine Stable.app/Contents/Resources/wine/bin/../lib/wine/i386-unix/ntdll.so, 2): Library not loaded: /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
  Referenced from: /Applications/Wine Stable.app/Contents/Resources/wine/lib/wine/i386-unix/ntdll.so
  Reason: no suitable image found.  Did find:
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit: mach-o, but wrong architecture
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit: mach-o, but wrong architecture
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit: mach-o, but wrong architecture
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit: mach-o, but wrong architecture
```
Can't seem to do much after trying. Trying to launch an installer for SWTOR for example, will show an additional
```
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: Internal error.
```
To the above error.

**Comment by Gcenx** [comment]
The issue seen here is wine attempting to load `i386-unix/ntdll.so` that requires 32Bit libraries, not sure _why_ this happened.

<br>

The games installer is 32Bit and won't launch with the current versions wine it requires some out of tree patches.

I did get the installer to launch but it eventually crashes matching the winehq entry https://appdb.winehq.org/objectManager.php?sClass=version&iId=34946.
