### ISSUE TITLE
Corrupted release for Wine Staging 8.5

### ISSUE THREAD

**Issue by hannesbraun** [Gcenx/macOS_Wine_builds#57]
The latest release of Wine Staging (8.5) seems to be corrupted. I cannot unpack the archive provided via GitHub releases. (See also [Homebrew/homebrew-cask-versions#15081](https://github.com/Homebrew/homebrew-cask-versions/actions/runs/4671189818/jobs/8271867271).)

*May be the same problem as in #47*

**Comment by Gcenx** [comment]
_Sigh_ I really wonder why this happens sometimes when uploading the release archives as each time is shows as if they’d uploaded correctly on the WebUI.

I’ll re-upload the archive later today.

**Comment by Gcenx** [comment]
@hannesbraun done, hopefully this re-upload it good

**Comment by hannesbraun** [comment]
Seems like it's working now, thanks :)
