### ISSUE TITLE
Wine 8.6 and 8.0.1 Releases?

### ISSUE THREAD

**Issue by semaja2** [Gcenx/macOS_Wine_builds#59]
Hi,

Is it possible to get the latest releases as they include a patch that fixes a issue introduced by latest MacOS update

Thanks

**Comment by Gcenx** [comment]
I’ve simply not had time to package the latest builds maybe during the weekend.

The macOS Ventura 13.3+ _fix_ was merged into wine-8.4 so the current wine-devel packages already works.

The latest wine-stable-8.0.1 had the macOS Ventura 13.3+ by my request.

**Comment by Gcenx** [comment]
i have wine-8.0.1/8.6/8.7 packages built juat need to upload them once my home internet is working
