### ISSUE TITLE
Broken on 10.13 High Sierra 

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [Gcenx/macOS_Wine_builds#61]
Hello :)

So, I was glad to find recent binaries for macOS, and super stoked that they apparently run on my 10.13.6 box.

However, I get this, both with the latest 8.7 staging build and the 8.0.1 stable build:

```
daniel@titanic  ~/Downloads/wino   /Applications/Wine\ Stable.app/Contents/MacOS/wine --help
dyld: lazy symbol binding failed: Symbol not found: _objc_opt_new
  Referenced from: /Applications/Wine Stable.app/Contents/MacOS/wine (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

dyld: Symbol not found: _objc_opt_new
  Referenced from: /Applications/Wine Stable.app/Contents/MacOS/wine (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

[1]    14375 abort      /Applications/Wine\ Stable.app/Contents/MacOS/wine --help
 ✘  daniel@titanic  ~/Downloads/wino
```

What gives? :'(

**Comment by Gcenx** [comment]
This really doesn’t make sense as the deployment target for this is set to 10.9 and I’m building and running these on macOS Mojave with the DevSDK from Xcode10 Command Line Tools that was the last thing to provide 32Bit support.

**Comment by Gcenx** [comment]
Reading over this again I can understand why your seeing this, you’ve attempted to launch the app bundles binary not the actual `wine` binary.

When you launch the app bundle the i386 slice will be used for macOS High Sierra and macOS Mojave, the x86_64 slice will be use for macOS Catalina and later.
