### ISSUE TITLE
New wine release builds? (8.8 8.9 8.10)

### ISSUE THREAD

**Issue by oscarbg** [Gcenx/macOS_Wine_builds#63]
No real need, just asking..

**Comment by austin987** [comment]
8.9 "Completion of PE conversion in the PostScript driver" https://www.winehq.org/announce/8.9
8.10 "All PE->Unix transitions go through the syscall interface" https://www.winehq.org/announce/8.10

Both should help with wow64, so it would be great to get a new build for at least 8.10 to be able to test this on macOS :)

**Comment by Gcenx** [comment]
I’ll need to check the Intel Mac and see if it still contains the 8.8 & 8.9 builds

If anything I’ll just take care of 8.10 packages with the minimum of macOS Sonoma fix since sooo many people upgraded there main rigs to this…..

**Comment by oscarbg** [comment]
For me would be nice a 8.10 release..Sounds like you are having problems with some of your hardware or you have switched machines? Hope not..

**Comment by Gcenx** [comment]
> For me would be nice a 8.10 release..Sounds like you are having problems with some of your hardware or you have switched machines? Hope not..

<br>

It’s a combination of factors.

My mid 2014 13in MacBook Pros SSD failed. someone did offer to send me one but what else will fail on that.

I do have a base M1 Mini but building i386 dylibs is pain.

And I’ve become busy with my job and life.

**Comment by Gcenx** [comment]
@oscarbg & @austin987 added wine-8.10 based packages that also include a patch to work on macOS Sonoma beta since so many users have upgraded.

These don't support "Apple Game Porting Toolkit - D3DMetal" though I'm tempted to add this, though Steam doesn't currently work under wow64 so that limits the games I can test to GOG releases.

**Comment by austin987** [comment]
Thanks @Gcenx! I wanted to do some testing on my mac, but I haven't managed to get the build environment working yet.

Seems to work for my initial purposes (winetricks -q dotnet40), which failed previously.

**Comment by alexsch01** [comment]
@Gcenx can you make a wine 8.12 build?

**Comment by oscarbg** [comment]
@Gcenx thannks for release and info.. just curious about d3dmetal .. I would say +10 to add D3DMetal support to your wine builds.. possibly to enable/disable via some Wine registry key (using regedit).. also I assume it work on Intel Macs (at least with AMD GPUs) since D3DMetal is a x64 library only since gpt 1.0.2

**Comment by Gcenx** [comment]
@oscarbg a coupe of things.

D3DMetal won’t work with wine-8.x due to update am changes, even if I rebased the wine side changes.

Secondly I couldn’t provide pre-modified packages, D3DMetal integration would need to take place on the users own system.

**Comment by oscarbg** [comment]
@Gcenx thanks for answering..
1. Don’t understand what you mean by “due to update am changes”.. any way, are you implying only wine-7.x builds could be provided with gpt enabled?
2. No problem, as long as you provide some guide for users to manually integrate..

**Comment by Gcenx** [comment]
@oscarbg sorry looks like autocorrect messed that up as usual somehow.

1. From what I can remember as I can't find the message now Apples stub dlls are calling the Unix libs using a function that was removed from wine-8.x, so the `Game porting toolkit` team would need to fix this and correctly rebase at the minimum changes to make D3DMetal useable.

2. Yes I'd provide details it's rather easy, Wineskin users are already able to use D3DMetal.
