### ISSUE TITLE
Will you be the official maintainer of MacOS wine builds?

### ISSUE THREAD

**Issue by alexsch01** [Gcenx/macOS_Wine_builds#64]
In https://wiki.winehq.org/Download, there is no maintainer for MacOS wine builds

**Comment by Gcenx** [comment]
@gverm & myself hadn't planned on pushing the packages to Winehq until the newer WoW64 became viable, where both the official Winehq macOS package maintainers see https://www.winehq.org/pipermail/wine-devel/2021-July/191504.html

The packages can be downloaded directly from this repo or installed via brews cask system as per Winehq documentation.

**Comment by alexsch01** [comment]
Thanks!
