### ISSUE TITLE
Update Wine 5.16

### ISSUE THREAD

**Issue by nevack** [Gcenx/macOS_Wine_builds#7]
https://www.winehq.org/announce/5.16

**Comment by Gcenx** [comment]
I don’t go off the Winehq announce but wine-staging

Packages are in the process of being built.

I will always update [macports-wine](https://github.com/Gcenx/macports-wine) first, then wine packages will usually follow

**Comment by Gcenx** [comment]
Both devel & staging packages are now available for download
