### ISSUE TITLE
macOS 

### ISSUE THREAD

**Issue by Smiril** [Gcenx/macOS_Wine_builds#98]
![Bildschirmfoto 2024-07-21 um 10 20 42](https://github.com/user-attachments/assets/d9a8e51b-8071-48a1-ac63-7a8e6486cf36)

brew installed wine-stable

**Comment by BaconWrappedShrimpWithEyes** [comment]
Either use `--no-quarantine` during install, or after seeing this error, open System Settings, navigate to Privacy and Security, scroll down, and click Allow where it says "Wine Stable" could not be run. (My apologies, I do not know what these settings are called in German)

Using Google Translate:
Verwenden Sie während der Installation entweder `--no-quarantine` oder öffnen Sie nach Auftreten dieses Fehlers die System Settings, navigieren Sie zu Privacy and Security, scrollen Sie nach unten und klicken Sie auf Zulassen, wo steht, dass "Wine Stable" nicht ausgeführt werden konnte. (Entschuldigung, ich weiß nicht, wie diese Einstellungen auf Deutsch heißen.)

**Comment by Smiril** [comment]
In „privacy & security“ i got only 
„AppStore and verified developer“ and this is chosen 
Better put in Building process a verified developer account and sign them

**Comment by Smiril** [comment]
--no-quarantine Cannot choosen because it installs with brew

there’s simply no developer for the app who has signed the application

**Comment by Smiril** [comment]
Make a fundraiser

**Comment by matthewyang204** [comment]
I don't sign my binaries either for the same reason. Apple Developer accounts are insanely expensive.
